### ISSUE TITLE
Deeptagger.dll missing?

### ISSUE THREAD

**Issue by danielvasic** [uwnlp/EasySRL#44]
While running, deeptagger.dll causes NullPointerException? Cannot find this library (deeptagger.dll) anywhere. Any help?
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at edu.uw.deeptagger.DeepTagger.loadLib(DeepTagger.java:54)
        at edu.uw.deeptagger.DeepTagger.loadFromJar(DeepTagger.java:35)
        at edu.uw.deeptagger.DeepTagger.<clinit>(DeepTagger.java:25)
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.makeDeepTagger(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.<init>(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.Tagger.make(Unknown Source)
        at edu.uw.easysrl.syntax.parser.ParserBuilder.build(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makePipelineParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.main(Unknown Source)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.makeDeepTagger(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.<init>(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.Tagger.make(Unknown Source)
        at edu.uw.easysrl.syntax.parser.ParserBuilder.build(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makePipelineParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.main(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to load required library: deeptagger.dll
        at edu.uw.deeptagger.DeepTagger.loadLib(DeepTagger.java:60)
        at edu.uw.deeptagger.DeepTagger.loadFromJar(DeepTagger.java:35)
        at edu.uw.deeptagger.DeepTagger.<clinit>(DeepTagger.java:25)
        ... 6 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at edu.uw.deeptagger.DeepTagger.loadLib(DeepTagger.java:54)
        ... 8 more

**Comment by kentonl** [comment]
Unfortunately, windows is not supported at this time, and we don't have the deeptagger.dll binary available.
